apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80
    resources:
        requests:
          cpu: "0.5"  # Request 0.5 CPU cores
          memory: "128Mi"  # Request 512 MB of memory
        limits:
          cpu: "1"  # Limit to 1 CPU core
          memory: "256Mi"  # Limit to 1 GB of memory