apiVersion: v1
kind: Service
metadata:
  name: voting-servis
  labels:
    name: voting-servis
    app: demo-voting-app
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: voting-app-pod
    app: demo-voting-app